### ISSUE TITLE
Actividad 10

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-equipo-mad#1]
[Actividad 10 - Conexión a bases de datos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-equipo-mad/files/15489248/Actividad.10.-.Conexion.a.bases.de.datos.pdf)

Integrantes:
Marlene Maricela Osorio Ramirez
Adriana Hernández Martínez
Daniel Velasco López

**Comment by josealfredo79** [comment]
Calificacion 18
